name: mazerunners
version: 1.0
main: me.JuliusH_1.mazerunners.Mazerunners
commands:
  mazerunner:
    description: Main command for the MazeRunners plugin
    usage: /mazerunner <start|respawn|spectate|teamspawn>