name: mazerunners
version: 1.0
main: me.JuliusH_1.mazerunners.Mazerunners
softdepend: [ItemsAdder]
api-version: 1.21
commands:
  mazerunner:
    description: Main command for the MazeRunners plugin
    usage: /mazerunner <start|respawn|spectate|teamspawn>